import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { useState, type MouseEventHandler } from "react";

import { api } from "~/utils/api";

import { Button, Drawer, Grid, Image, User, Page } from "@geist-ui/core";
import { useToasts} from "@geist-ui/core";
import { useTheme } from '@geist-ui/core'

interface HomeProps {
  switchThemes: MouseEventHandler<HTMLButtonElement>;
  themeType: {
    type: string
  };
}

const Home: NextPage<HomeProps> = ({ switchThemes, themeType}) => {

  const theme = useTheme()
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const [drawerOpen, setDrawerOpen] = useState(false) 

  const { setToast } = useToasts()
  const showToast = () => setToast({ text: 'Hello, user!', delay: 2000 , type:"success"})
  
  console.log(themeType)

  
  return (
   
    <>
      <Head>
        <title>Gymn</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={themeType.type == "Dark" ? "dark" : ""}>
        <main className={`flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#00000000] bg-purple-300 dark:bg-neutral-950` } color="">
          <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="container flex flex-col items-center justify-center h-14 lg:h-24">
            <Image height="100%" src="/gymn_WhiteTextLogo.svg" alt=''/>
          </div>
          
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
              <Link
                className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                href="https://create.t3.gg/en/usage/first-steps"
                target="_blank"
              >
                <h3 className="text-2xl font-bold">First Steps →</h3>
                <div className="text-lg">
                  Just the basics - Everything you need to know to set up your
                  database and authentication.
                </div>
              </Link>
              <Link
                className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                href="https://create.t3.gg/en/introduction"
                target="_blank"
              >
                <h3 className="text-2xl font-bold">Documentation →</h3>
                <div className="text-lg">
                  Learn more about Create T3 App, the libraries it uses, and how
                  to deploy it.
                </div>
              </Link>
            </div>
            <p className="text-2xl text-white">
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p>

            <Grid.Container justify="center" >            
              <Button auto type="success" onClick={showToast}>Toast</Button>
              <Button auto type="secondary" onClick={() => setDrawerOpen(true)}>Drawer</Button>
            </Grid.Container>          

            <Drawer visible={drawerOpen} onClose={() => setDrawerOpen(false)} placement="right">
              <Drawer.Title>Drawer</Drawer.Title>
              <Drawer.Subtitle>This is a drawer</Drawer.Subtitle>
              <Drawer.Content>
                <p>Some content contained within the drawer.</p>
                <Button width={"100%"} onClick={() => setDrawerOpen(false)}>Close</Button>
              </Drawer.Content>
            </Drawer>
            <div>
              <User src="https://avatars.githubusercontent.com/u/102877738?v=4" name="Ricardo Amorim">
                <User.Link href="https://github.com/risixdzn">@risixdzn</User.Link>
              </User>
            </div>

            <Button type='secondary' ghost auto scale={0.75} onClick={switchThemes}>Change Theme</Button>
            
          </div>
        </main>
      </div>      
    </>
  );
};

export default Home;
