import Head from 'next/head'
import Image from 'next/image'

import ComingSoon from '../public/comingsoon.png'

export default function Home() {
  return (
    <>
      <Head>
        <title>Gymn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-screen w-full overflow-hidden bg-neutral-1000 flex items-center content-center'>
        <Image width={1000} height={"auto"} src={ComingSoon} className='mx-auto'/>
      </main>
    </>
  )
}
